import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import AppLayout from "../../components/layout/AppLayout";
import { createQuiz } from "../../services/quizService";

const blankQuestion = () => ({ question: "", options: ["", "", "", ""], correctAnswer: "", type: "multiple" });
function CreateQuiz() { const [form, setForm] = useState({ title: "", category: "", difficulty: "easy", questions: [blankQuestion()] }); const [state, setState] = useState({ loading: false, error: "" }); const navigate = useNavigate();
  const updateQuestion = (index, key, value) => setForm((prev) => ({ ...prev, questions: prev.questions.map((question, questionIndex) => questionIndex === index ? { ...question, [key]: value } : question) }));
  const updateOption = (questionIndex, optionIndex, value) => setForm((prev) => ({ ...prev, questions: prev.questions.map((question, index) => index === questionIndex ? { ...question, options: question.options.map((option, itemIndex) => itemIndex === optionIndex ? value : option) } : question) }));
  const submit = async (event) => { event.preventDefault(); setState({ loading: true, error: "" }); const questions = form.questions.map((question) => ({ ...question, options: question.options.filter(Boolean) })); try { await createQuiz({ ...form, questions, totalQuestions: questions.length }); navigate("/admin/quizzes"); } catch (err) { setState({ loading: false, error: err.message }); } };
  return <AppLayout><div className="container create-wrap"><Link className="back-link" to="/admin">← Admin workspace</Link><div className="page-heading"><div><p className="eyebrow">New content</p><h1>Create a quiz</h1></div></div><form className="create-form" onSubmit={submit}><div className="panel form-grid"><label className="field">Title<input required value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></label><div className="form-two"><label className="field">Category<input required value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })} /></label><label className="field">Difficulty<select value={form.difficulty} onChange={(e) => setForm({ ...form, difficulty: e.target.value })}><option value="easy">Easy</option><option value="medium">Medium</option><option value="hard">Hard</option></select></label></div></div>{form.questions.map((question, index) => <div className="panel question-builder" key={index}><div className="builder-heading"><span className="eyebrow">Question {index + 1}</span>{form.questions.length > 1 && <button type="button" className="text-button" onClick={() => setForm((prev) => ({ ...prev, questions: prev.questions.filter((_, itemIndex) => itemIndex !== index) }))}>Remove</button>}</div><label className="field">Prompt<textarea required value={question.question} onChange={(e) => updateQuestion(index, "question", e.target.value)} /></label><div className="options-grid">{question.options.map((option, optionIndex) => <label className="field" key={optionIndex}>Option {optionIndex + 1}<input required value={option} onChange={(e) => updateOption(index, optionIndex, e.target.value)} /></label>)}</div><label className="field">Correct answer<select required value={question.correctAnswer} onChange={(e) => updateQuestion(index, "correctAnswer", e.target.value)}><option value="">Select correct answer</option>{question.options.filter(Boolean).map((option) => <option key={option} value={option}>{option}</option>)}</select></label></div>)}<button type="button" className="button button-secondary" onClick={() => setForm((prev) => ({ ...prev, questions: [...prev.questions, blankQuestion()] }))}>+ Add question</button>{state.error && <p className="error-text">{state.error}</p>}<button className="button button-primary" disabled={state.loading}>{state.loading ? "Publishing..." : "Publish quiz"}</button></form></div></AppLayout>;
}

export default CreateQuiz;
